
export const Productos = [
    {
        id: 1,
        Categoria: "StarWars",
        Nombre: "Boba Fett", 
        Descripcion: "Boba Fett cazara la atencion de quien ingrese a tu casa al punto que no querra irse sin tomarle una foto", 
        precio: 500, 
        stock : 10,
        img: "https://res.cloudinary.com/dntew63nw/image/upload/v1671572213/1_uotvcu.jpg",
    },
    {
        id: 2,
        Categoria:"StarWars",
        Nombre: "Trooper", 
        Descripcion: "Troopers con grandes estilos realzaran tu habitacion pero cuidado con mirar a los ojos a mitico Darth Vader", 
        precio: 500, 
        stock : 15,
        img:"https://res.cloudinary.com/dntew63nw/image/upload/v1671572213/2_unnqfw.jpg",
    },
    {
        id: 3,
        Categoria:"StarWars",
        Nombre: "Maestro Yoda", 
        Descripcion: "Maestro Yoda guiara con la fuerza la atencion de quien lo mire, seguramente no dejen de mirarlo", 
        precio: 500, 
        stock : 8,
        img: "https://res.cloudinary.com/dntew63nw/image/upload/v1671572213/3_cdrr7q.jpg",
    },
    {
        id: 4,
        Categoria: "LordOfTheRings",
        Nombre: "Sauron", 
        Descripcion: " Sauron guiara al lado oscuro con sus ojos, pero seguro que alguien preguntara donde compraste ese cuadro", 
        precio: 500, 
        stock : 13,
        img: "https://res.cloudinary.com/dntew63nw/image/upload/v1671572213/4_zb1aqh.jpg",
    },
    {
        id: 5,
        Categoria: "LordOfTheRings",
        Nombre: "La Gran Batalla", 
        Descripcion: "El encanto de Grogu o baby Yoda, no importa como lo llamen el siempre tendra tu atencion", 
        precio: 500, 
        stock : 5,
        img: "https://res.cloudinary.com/dntew63nw/image/upload/v1671572213/5_nq46vd.jpg",
    },
    {
        id: 6,
        Categoria: "LordOfTheRings",
        Nombre: "El largo Camino", 
        Descripcion: "El largo camino que llevo a la comunidad a enfrentar sus mas grandes temores", 
        precio: 500, 
        stock : 3,
        img: "https://res.cloudinary.com/dntew63nw/image/upload/v1671572213/6_lfb5tp.jpg",
    },
    {
        id: 7,
        Categoria: "Pokemon",
        Nombre: "Reunion Pokemon", 
        Descripcion: "En este hermoso cuadro se encuentran reunidos todos los pokemones que un dia tuvo Ash", 
        precio: 500, 
        stock : 6,
        img: "https://res.cloudinary.com/dntew63nw/image/upload/v1671572214/7_y7jkwm.jpg",
    },
    {
        id: 8,
        Categoria: "Pokemon",
        Nombre: "Pikachu Pensativo", 
        Descripcion: "Solo Picachu nos puede trasmitir un momento de tranquilidad o pensamientos propios", 
        precio: 500, 
        stock : 32,
        img: "https://res.cloudinary.com/dntew63nw/image/upload/v1671572214/8_qknxml.jpg",
    },
    {
        id: 9,
        Categoria: "Pokemon",
        Nombre: "Los Iniciales", 
        Descripcion: "Un cuadro donde nos hara recordar cuales fueron los Pokemon iniciales una dificil decision de cualquier maestro pokemon", 
        precio: 500, 
        stock : 18,
        img: "https://res.cloudinary.com/dntew63nw/image/upload/v1671572213/9_uvfhp0.jpg",
    },
]