
export const Productos = [
    {
        Id: 1,
        Categoria: "StarWars",
        Nombre: "Boba Fett", 
        Descripcion: "Boba Fett cazara la atencion de quien ingrese a tu casa al punto que no querra irse sin tomarle una foto", 
        precio: 500, 
        stock : 10,
        img: "./images/1.jpg",
    },
    {
        Id: 2,
        Categoria:"StarWars",
        Nombre: "Trooper", 
        Descripcion: "Troopers con grandes estilos realzaran tu habitacion pero cuidado con mirar a los ojos a mitico Darth Vader", 
        precio: 500, 
        stock : 15,
        img:"./images/2.jpg",
    },
    {
        Id: 3,
        Categoria:"StarWars",
        Nombre: "Maestro Yoda", 
        Descripcion: "Maestro Yoda guiara con la fuerza la atencion de quien lo mire, seguramente no dejen de mirarlo", 
        precio: 500, 
        stock : 8,
        img: "./images/3.jpg",
    },
    {
        Id: 4,
        Categoria: "LordOfTheRings",
        Nombre: "Sauron", 
        Descripcion: "Darth Vader guiara al lado oscuro con sus ojos no tan oscuros, pero seguro que alguien preguntara donde compraste ese cuadro", 
        precio: 500, 
        stock : 13,
        img: "./images/4.jpg",
    },
    {
        Id: 5,
        Categoria: "LordOfTheRings",
        Nombre: "La Gran Batalla", 
        Descripcion: "El encanto de Grogu o baby Yoda, no importa como lo llamen el siempre tendra tu atencion", 
        precio: 500, 
        stock : 5,
        img: "./images/5.jpg",
    },
    {
        Id: 6,
        Categoria: "LordOfTheRings",
        Nombre: "El largo Camino", 
        Descripcion: "Darth Vader en su maximo explendor te guiara al lado oscuro con solo mirarlo", 
        precio: 500, 
        stock : 3,
        img: "./images/6.jpg",
    },
    {
        Id: 7,
        Categoria: "Pokemon",
        Nombre: "Reunion Pokemon", 
        Descripcion: "Boba Fett cazara la atencion de quien ingrese a tu casa al punto que no querra irse sin tomarle una foto", 
        precio: 500, 
        stock : 6,
        img: "./images/7.jpg",
    },
    {
        Id: 8,
        Categoria: "Pokemon",
        Nombre: "Pikachu Pensativo", 
        Descripcion: "Boba Fett cazara la atencion de quien ingrese a tu casa al punto que no querra irse sin tomarle una foto", 
        precio: 500, 
        stock : 32,
        img: "./images/8.jpg",
    },
    {
        Id: 9,
        Categoria: "Pokemon",
        Nombre: "Los Iniciales", 
        Descripcion: "Boba Fett cazara la atencion de quien ingrese a tu casa al punto que no querra irse sin tomarle una foto", 
        precio: 500, 
        stock : 18,
        img: "./images/9.jpg",
    },
]